language: node_js
deploy:
  provider: s3
  access_key_id: ${AWS_ACCESS_KEY}
  secret_access_key: ${AWS_SECRET_KEY}
  bucket: "fumentool"
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    condition: $TRAVIS_TAG = v0.0.1
