language: node_js
before_deploy:
  - cp -r src/ build/
deploy:
  provider: s3
  access_key_id: ${AWS_ACCESS_KEY}
  secret_access_key: ${AWS_SECRET_KEY}
  region: ap-northeast-1
  bucket: fumentool
  acl: public_read
  local_dir: build
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    condition: $TRAVIS_TAG =~ ^v[0-9\\.]+
